### ISSUE TITLE
Calibrate a new quadrotor model

### ISSUE THREAD

**Issue by ke-sun** [kartikmohta/qualisys#4]
@kartikmohta 

Since it is not easy to identify the markers of a model in qualisys, I am thinking directly store the homogeneous transformation between the centroid of the markers on a calib stand and the geometric center of the calib stand, which can achieve the same purpose during the calibration.

**Comment by kartikmohta** [comment]
I don't think using a calib stand is very feasible anyways since you need a different calib stand for each robot type. And in the outdoor setup we'll be using a lot of different types of robots anyway.
The main reason to use a calib stand is to get the orientation (mainly yaw) correct when the model is created with the robot frame not aligned with the reference frame. Maybe we need to think of a different way to solve this.

**Comment by kartikmohta** [comment]
I guess this is not really relevant now.
